spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dima
    username: dima
    password: dima
  liquibase:
    changeLog: "classpath:db/changeset.yaml"